// Generated by CoffeeScript 1.7.1

/*


 File: genes_info.coffee
 Desc: Javascript functions for the genes/info page
 Author: Matt Whiteside matthew.whiteside@phac-aspc.gc.ca
 Date: May 27th, 2013
 */

(function() {
  var categoryView, root, _categoryHtml;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  categoryView = function(categoryObj, el) {
    var genHtml, html, midHtml, topHtml, wrapEl;
    html = '<div class="gene-info-category-wrapper">';
    topHtml = _categoryHtml(categoryObj.top, true);
    html += "<div class='top-category'>" + topHtml + "</div>";
    midHtml = _categoryHtml(categoryObj.category);
    html += "<div class='middle-category'>" + midHtml + "</div>";
    genHtml = _categoryHtml(categoryObj.gene);
    html += "<div class='gene-category'>" + genHtml + "</div>";
    return wrapEl = jQuery(html).appendTo(el);
  };

  if (!root.categoryView) {
    root.categoryView = categoryView;
  }

  _categoryHtml = function(catObj, top) {
    var header, html;
    if (top == null) {
      top = false;
    }
    header = catObj.name[0].toUpperCase() + catObj.name.slice(1);
    return html = ("<h5><i class='fa fa-chevron-right'></i> " + header + "</h5>") + ("<p>" + catObj.definition + "</p>");
  };

}).call(this);
