// Generated by CoffeeScript 1.7.1

/*


 File: genes_search.coffee
 Desc: Javascript functions for the genes/search page
 Author: Matt Whiteside matthew.whiteside@phac-aspc.gc.ca
 Date: May 16th, 2013
 */

(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.initGeneList = function(gList) {
    var k, o, _results;
    _results = [];
    for (k in gList) {
      o = gList[k];
      o.visible = true;
      _results.push(o.selected = false);
    }
    return _results;
  };

  root.appendGeneList = function(gList, elem, listType) {
    var id, item, k, o, _results;
    if (!(listType === 'vf' || listType === 'amr')) {
      throw new Error("Invalid listType parameter: " + listType + ".");
    }
    _results = [];
    for (k in gList) {
      o = gList[k];
      if (o.visible) {
        id = "" + listType + "_gene_" + k;
        item = jQuery("<li><label class='checkbox'><input id='" + id + "' class='checkbox' type='checkbox' value='" + k + "' name='selected-" + listType + "' />" + o.name + " - " + o.uniquename + "</label></li>");
        if (o.selected) {
          item.prop('checked', true);
        }
        _results.push(elem.append(item));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

}).call(this);
