// Generated by CoffeeScript 1.8.0

/*


 File: intro_home.coffee
 Desc: CoffeeScript for home page intro
 Author: Jason Masih jason.masih@phac-aspc.gc.ca
 Date: Sept 9, 2014
 

 Name all files like this intro_[page_name].coffee

 Compiled coffeescript files will be sent to App/Lib/js/. This directory
 contains all Superphy's js files. So this naming scheme will help ensure 
 there are no filename collisions.

 Cakefile has a routine to compile and output the coffeescript files
 in intro/ to js/. To run:

   cake intro
 */

(function() {
  var root, startIntro;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  startIntro = function() {
    var intro;
    intro = introJs();
    intro.setOptions({
      steps: [
        {
          intro: "Welcome to SuperPhy.  Use the navigation bar to get started."
        }
      ]
    });
    intro.start();
    return false;
  };

  if (!root.startIntro) {
    root.startIntro = startIntro;
  }

}).call(this);
