// Generated by CoffeeScript 1.8.0

/*


 File: intro_strains_search.coffee
 Desc: CoffeeScript for strains/search page intros
 Author: Jason Masih jason.masih@phac-aspc.gc.ca
 Date: Sept 5, 2014
 

 Name all files like this intro_[page_name].coffee

 Compiled coffeescript files will be sent to App/Lib/js/. This directory
 contains all Superphy's js files. So this naming scheme will help ensure 
 there are no filename collisions.

 Cakefile has a routine to compile and output the coffeescript files
 in intro/ to js/. To run:

   cake intro
 */

(function() {
  var root, startIntro;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  startIntro = function() {
    var intro, opts;
    window.scrollTo(0, 0);
    opts = viewController.introOptions();
    opts.splice(0, 0, {
      intro: "You can use this page to search for information about the genomes in the database."
    });
    opts.splice(1, 0, {
      element: document.querySelector('#genomes-menu-affix'),
      intro: "You can perform a search in three different ways: using the genome list, phylogenetic tree, or map.",
      position: 'bottom'
    });
    intro = introJs();
    intro.setOptions({
      steps: opts
    });
    intro.start();
    return false;
  };

  if (!root.startIntro) {
    root.startIntro = startIntro;
  }

}).call(this);
