// Generated by CoffeeScript 1.7.1

/*
    CLASS Poller
 */
var Poller;

Poller = (function() {
  function Poller(jobId, alertStatusDiv) {
    this.jobId = jobId;
    this.alertStatusDiv = alertStatusDiv;
    if (this.jobId == null) {
      throw new SuperphyError('Job id must be specified in Poller constructor');
    }
    if (this.alertStatusDiv == null) {
      throw new SuperphyError('Need to specify status div for Poller constructor');
    }
  }

  Poller.prototype.pollJob = function() {
    jQuery.ajax({
      type: 'POST',
      url: '/groups/poll/',
      data: {
        'job_id': this.jobId
      }
    }).done(function(data) {
      return console.log(data);
    });
    return true;
  };

  return Poller;

})();
